#!/usr/bin/env python
#
# Sample ntris_ai exectuable.
#

import json
import time
import sys

if __name__ == '__main__':
   if len(sys.argv) == 2:
      game_state = json.loads(sys.argv[1]) # The game state is passed in as a json blob.
      print 'left'                         # Print your moves to standard out and they'll be sent up to our game server.
      sys.stdout.flush()                   # We flush standard out to make sure moves are communicated to the game server immediately.
      time.sleep(11)                       # Do a bunch of fancy AI computation!
      print 'right'                        # We exceeded the timeout, so this move won't actually get sent up to the server!
      sys.stdout.flush()