#!/usr/bin/env python
#
# Sample ntris_ai exectuable
#

import json
import time
import sys

if __name__ == '__main__':
	if len(sys.argv) == 2:
		game_state = json.loads(sys.argv[1])
		print 'left'
		sys.stdout.flush()
		time.sleep(11)
		print 'right'
		sys.stdout.flush()