#!/usr/bin/env python
#
# Defines constants used in our client-server
# messaging protocol.
#

CREATE_NEW_GAME_MSG = 'CREATE_NEW_GAME'
NEW_GAME_CREATED_MSG = 'NEW_GAME_CREATED'
AWAITING_NEXT_MOVE_MSG = 'AWAITING_NEXT_MOVE'
SUBMIT_MOVE_MSG = 'SUBMIT_MOVE'
GAME_OVER_MSG = 'GAME_OVER'
DO_NOT_RECONNECT = 1001